apiVersion: apps/v1 
kind: Deployment
metadata:
  name: process-demo-ui-deployment
spec:
  selector:
    matchLabels:
      app: process-demo-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: process-demo-ui
    spec:
    #  nodeSelector:
    #    dedicated: master
      containers:
      - name: process-demo-ui
        image: tbiernat/process-demo-ui 
